apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
        command: ["/bin/sh"]
        args: ["-c", "echo you are on NGIX-server: $HOSTNAME > /usr/share/nginx/html/index.html && exec nginx -g 'daemon off;'"]
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/conf.d
      volumes:
        - name: nginx-config-volume
          configMap:
            name: nginx-cfgmap
---
kind: Service
apiVersion: v1
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
  type: LoadBalancer
---
apiVersion: v1
data:
  default.conf: |
    server {
       listen       80;
       server_name  localhost;
       #return 301 https://dou.ua/;
       #charset koi8-r;
       #access_log  /var/log/nginx/log/host.access.log  main;

       location / {
           root   /usr/share/nginx/html;
           index  index.html index.htm;
       }

       error_page   500 502 503 504  /50x.html;
       location = /50x.html {
           root   /usr/share/nginx/html;
       }
          }
kind: ConfigMap
metadata:
  name: nginx-cfgmap
  namespace: default
  selfLink: /api/v1/namespaces/default/configmaps/nginx-cfgmap